**Install PyTorch**
PyTorch is already installed in most Google Colab environments.

In [ ]:
# Install PyTorch for CPU Version
!pip install torch torchvision torchaudio

In [12]:
# CUDA Version
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121


In [ ]:
import torch

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.11.0+cpu


In [ ]:
# Import Library
import torch
import numpy as np

**Creating Tensors**

In [1]:
# Scalar Tensor
import torch

x = torch.tensor(10)

print(x)

tensor(10)


In [2]:
# Vector Tensor
x = torch.tensor([1,2,3])

print(x)

tensor([1, 2, 3])


In [3]:
# Matrix Tensor
x = torch.tensor([
    [1,2],
    [3,4]
])

print(x)

tensor([[1, 2],
        [3, 4]])


In [4]:
# Tensor Shape (Shape describes the size of each dimension.)
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(x.shape)

# 2 rows
# 3 columns

torch.Size([2, 3])


In [5]:
# Tensor Dimensions
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(x.ndim)

2


In [6]:
# Tensor Data Types (Every tensor stores values using a specific data type.)
x = torch.tensor([1,2,3])

print(x.dtype)

torch.int64


Common dtypes:
# Type	      Description
*   torch.int32	= Integer
*   torch.int64	= Long Integer
*   torch.float32	= Float
*   torch.float64	= Double
*   torch.bool	= Boolean

# **Creating Tensors with Different Initializations**

In [7]:
# Zeros
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# Ones
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# Random Uniform
torch.rand((3,3))

tensor([[0.7125, 0.8109, 0.6796],
        [0.7478, 0.7176, 0.3211],
        [0.4095, 0.2919, 0.2127]])

In [10]:
# Random Gaussian
torch.randn((3,3))

tensor([[-1.0523,  0.1677, -0.8211],
        [ 1.0422, -0.2283,  0.5757],
        [ 0.9129,  0.2690,  0.2941]])