**Install PyTorch**
PyTorch is already installed in most Google Colab environments.

In [ ]:
# Install PyTorch for CPU Version
!pip install torch torchvision torchaudio

In [ ]:
# CUDA Version
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121


In [2]:
import torch

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.11.0+cpu


In [4]:
# Import Library
import torch
import numpy as np

# **Tensor Operations**

In [6]:
# Addition

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

c = a + b

print(c)

tensor([5, 7, 9])


In [7]:
# Multiplication

a * b

tensor([ 4, 10, 18])

**Matrix Multiplication**
Deep learning heavily relies on matrix multiplication.

In [8]:
A = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

B = torch.tensor([
    [5,6],
    [7,8]
], dtype=torch.float32)

C = torch.matmul(A,B)

print(C)

tensor([[19., 22.],
        [43., 50.]])


**Tensor Reshaping**

Often required before feeding data into neural networks.

In [9]:
x = torch.arange(12)

print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [10]:
# Reshape
x = x.reshape(3,4)

print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


**NumPy and PyTorch Interoperability**
NumPy → Tensor

In [11]:
# NumPy → Tensor

import numpy as np

arr = np.array([1,2,3])

tensor = torch.from_numpy(arr)

In [ ]:
# Tensor → NumPy
tensor.numpy()

**Automatic Differentiation (Autograd)**
One of PyTorch's most powerful features.
Autograd automatically computes derivatives required during neural network training.

Consider:

y=x^2

In [12]:
# Creating a Differentiable Tensor
x = torch.tensor(
    2.0,
    requires_grad=True
)

In [13]:
# Computing Gradients
y = x**2

y.backward()

print(x.grad)

tensor(4.)
